name: Build/Deploy CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint, type checks and tests
        run: yarn verify

      - name: Yarn build
        run: yarn build

  pre_release:
    runs-on: ubuntu-latest
    needs: build

    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
          registry-url: "https://registry.npmjs.org"


      - name: Install dependencies
        run: yarn install --immutable

      - name: Version
        run: npm version --no-git-tag-version "$(node -e "console.log(require('./package.json').version)")-pre.${{ github.run_number }}"

      - name: Run lint, type checks and tests
        run: yarn verify

      - name: Yarn build
        run: yarn build


      - name: Pre-release
        run: yarn run ci:prepublish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}


