name: Build/Deploy CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - created


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint, type checks and tests
        run: yarn verify

      - name: Yarn build
        run: yarn build

  pre_release:
    runs-on: ubuntu-latest
    needs: build

    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
          registry-url: "https://registry.npmjs.org"


      - name: Install dependencies
        run: yarn install --immutable

      - name: Version
        run: yarn version "$(node -e "console.log(require('semver').inc(require('./package.json').version, 'patch'))")-pre.${{ github.run_number }}"

      - name: Run lint, type checks and tests
        run: yarn verify

      - name: Yarn build
        run: yarn build

      - run: git config user.email "noreply@icrc.org" && git config user.name "CI"
      - run: git add . && git commit -m "Prerelease version" --no-verify

      - name: Pre-release
        run: yarn config set npmAuthToken "${NODE_AUTH_TOKEN}" && yarn run ci:prepublish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}


