name: openmrs-esm-patient-grid CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

#env:
#  ESM_NAME: "@icrc/openmrs-esm-patient-grid"
#  JS_NAME: "openmrs-esm-patient-grid.js"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: yarn
      - run: yarn lint
      - run: yarn coverage
      - run: yarn typescript
      - run: yarn build
