name: openmrs-esm-patientgrid Publish


on:
  push:
    branches:
      - 'publish-package'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - name: Use Node.js
         uses: actions/setup-node@v3
         with:
           node-version: "18.x"
           registry-url: 'https://npm.pkg.github.com'
           cache: 'yarn'
       - run: yarn install --immutable
       - run: yarn verify
#         yarn 3 version is buggy and try to do some git tag but don't support the option --no-git-tag-version. So we use npm version
#       - run: yarn plugin import version
       - run: npm version --no-git-tag-version "$(node -e "console.log(require('semver').inc(require('./package.json').version, 'patch'))")-pre.${{ github.run_number }}"
       - run: yarn build
       - run: yarn npm publish
         env:
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           required by yarn
           YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           YARN_NPM_REGISTRY_SERVER: "https://npm.pkg.github.com"
