name: openmrs-esm-patientgrid Release

on:
  release:
    types: [created]


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - name: Download Artifacts
         uses: actions/download-artifact@v3
       - name: Use Node.js
         uses: actions/setup-node@v3
         with:
           node-version: "18.x"
           registry-url: 'https://npm.pkg.github.com'
           cache: 'yarn'
       - run: yarn install --immutable
       - run: yarn verify
       - run: yarn build
       - run: yarn npm publish
         env:
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           required by yarn
           YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           YARN_NPM_REGISTRY_SERVER: "https://npm.pkg.github.com"
